//! Test helpers for persistence modules.
#![allow(clippy::many_single_char_names, clippy::cast_possible_truncation)]
//!
//! Small, stable helpers that tests across the workspace can consume
//! without duplicating boilerplate.

use std::time::Duration;

use rand::RngCore;
use rand::SeedableRng;
use rand::rngs::StdRng;

use super::{Context, InMemoryDriver};

/// Return a fresh `InMemoryDriver` for use in tests.
#[must_use]
pub fn memory_driver() -> InMemoryDriver {
    InMemoryDriver::new()
}

/// Return a pre-populated `InMemoryDriver` seeded with the provided pairs.
#[must_use]
pub fn memory_driver_with_seed(entries: &[(&str, &str)]) -> InMemoryDriver {
    let drv = InMemoryDriver::new();
    let _ = drv.seed(
        entries
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string())),
    );
    drv
}

/// Create a `Context` with a deadline `ms` milliseconds from now.
#[must_use]
pub fn ctx_with_timeout_ms(ms: u64) -> Context {
    Context::with_deadline_from_now(Duration::from_millis(ms))
}

/// Create a `Context` whose deadline is immediately expired.
/// Useful to test deadline handling without sleeping.
#[must_use]
pub fn expired_ctx() -> Context {
    Context::with_deadline_from_now(Duration::from_millis(0))
}

/// Spawn `writers` concurrent tasks that each write `ops_per_writer` entries.
/// Keys are produced as `{key_prefix}-{writer_index}-{op_index}` and values
/// as `{value_prefix}-{writer_index}-{op_index}`. This helper awaits all
/// spawned tasks and returns when complete.
pub async fn concurrent_writers(
    drv: InMemoryDriver,
    writers: usize,
    ops_per_writer: usize,
    key_prefix: &str,
    value_prefix: &str,
) {
    let mut handles = Vec::with_capacity(writers);
    for w in 0..writers {
        let d = drv.clone();
        let kp = key_prefix.to_string();
        let vp = value_prefix.to_string();
        handles.push(tokio::spawn(async move {
            for i in 0..ops_per_writer {
                let key = format!("{kp}-{w}-{i}");
                let val = format!("{vp}-{w}-{i}");
                // ignore put errors in test harness (should not happen)
                let _ = d.put(&key, &val);
            }
        }));
    }

    for h in handles {
        let _ = h.await;
    }
}

/// Spawn `readers` concurrent tasks that each read all keys generated by
/// `writers * ops_per_writer` with the same key prefix. Returns the total
/// number of successful reads observed across all reader tasks.
pub async fn concurrent_readers(
    drv: InMemoryDriver,
    readers: usize,
    writers: usize,
    ops_per_writer: usize,
    key_prefix: &str,
) -> usize {
    let mut handles = Vec::with_capacity(readers);
    for _ in 0..readers {
        let d = drv.clone();
        let kp = key_prefix.to_string();
        handles.push(tokio::spawn(async move {
            let mut found = 0usize;
            for w in 0..writers {
                for i in 0..ops_per_writer {
                    let key = format!("{kp}-{w}-{i}");
                    if d.get(&key).is_some() {
                        found += 1;
                    }
                }
            }
            found
        }));
    }

    let mut total = 0usize;
    for h in handles {
        if let Ok(v) = h.await {
            total += v;
        }
    }
    total
}

/// Run a randomized stress test for `duration_secs` seconds.
///
/// - `seed`: optional RNG seed for determinism.
/// - `writers`/`readers`: number of concurrent tasks.
/// - `key_space`: number of distinct keys (0..key_space-1) each writer chooses from.
/// - `put_prob`: probability (0.0..1.0) that an operation is a `put` vs `get`/`delete`.
pub async fn randomized_stress(
    drv: InMemoryDriver,
    duration_secs: u64,
    seed: Option<u64>,
    writers: usize,
    readers: usize,
    key_space: usize,
    put_prob: f64,
) {
    let rng_seed = seed.unwrap_or_else(rand::random::<u64>);
    let stop_at = tokio::time::Instant::now() + Duration::from_secs(duration_secs);

    let mut handles = Vec::new();

    // writers
    for w in 0..writers {
        let d = drv.clone();
        let s = rng_seed.wrapping_add(w as u64);
        let ks = key_space;
        let pp = put_prob;
        handles.push(tokio::spawn(async move {
            let mut rng = StdRng::seed_from_u64(s);
            // Use direct RNG calls to avoid multiple mutable borrows from closures.
            while tokio::time::Instant::now() < stop_at {
                let kidx = (rng.next_u32() % (ks as u32)) as usize;
                let k = format!("rk-{kidx}-{w}");
                let p = f64::from(rng.next_u32()) / (f64::from(u32::MAX) + 1.0);
                if p < pp {
                    let v = format!("rv-{}", u64::from(rng.next_u32()));
                    let _ = d.put(&k, &v);
                } else if p < pp + 0.1 {
                    let _ = d.delete(&k);
                } else {
                    let _ = d.get(&k);
                }
                // small jitter
                tokio::time::sleep(Duration::from_millis(1)).await;
            }
        }));
    }

    // readers
    for r in 0..readers {
        let d = drv.clone();
        let s = rng_seed.wrapping_add((r + writers) as u64);
        let ks = key_space;
        handles.push(tokio::spawn(async move {
            let mut rng = StdRng::seed_from_u64(s);
            let mut rand_range = |bound: u32| (rng.next_u32() % bound) as usize;
            while tokio::time::Instant::now() < stop_at {
                let k = format!(
                    "rk-{}-{}",
                    rand_range(ks as u32),
                    rand_range(writers as u32)
                );
                let _ = d.get(&k);
                tokio::time::sleep(Duration::from_millis(1)).await;
            }
        }));
    }

    // await all
    for h in handles {
        let _ = h.await;
    }
}
