global:
  scrape_interval: 5s     # how often Prometheus scrapes targets
  evaluation_interval: 5s

scrape_configs:
  # ─── Scrape Mint ────────────────────────────────
  - job_name: 'robot'
    static_configs:
      - targets: ['robot:9090']
    metrics_path: /metrics

  # ─── Scrape Prometheus itself ───────────────────
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

