NATS_PORT=8005
METRICS_PORT=8015
GRAFANA_PORT=8025


ROBOT_GATEWAY_PORT=9000
AGGREGATOR_SERVICE_PORT=9010
REFINERY_SERVICE_PORT=9020
MINT_SERVICE_PORT=9030
VAULT_SERVICE_PORT=9040
WALLET_SERVICE_PORT=9050
TRUST_SERVICE_PORT=9060
BIDNET_SERVICE_PORT=9070


