#!/usr/bin/env python3
"""
E2E Test: Phase 4 Crypto Pipeline Flow
Tests complete data flow with crypto signatures:
Digger → Refinery → Mint → DistoDam

This test validates that crypto signatures are:
1. Generated by Digger (Falcon-1024)
2. Transmitted in NATS messages
3. Processed through the pipeline
4. Included in Phase3RoboTorqUnit (SPHINCS+)

WARNING: This test validates STRUCTURE and FLOW, NOT cryptographic validity.
The Refinery and Mint use PLACEHOLDER verification that accepts ALL signatures.
This is okay for development but CRITICAL to fix before production.
"""

import asyncio
import json
import sys
import os
import time

# Add fixtures to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from fixtures.helpers import *

NATS_URL = "nats://localhost:4222"
DIGGER_API = "http://localhost:3030"
REFINERY_CONTAINER = "robotorq-network-refinery-1"
MINT_CONTAINER = "robotorq-network-mint-1"
DISTODAM_CONTAINER = "robotorq-network-distodam-1"

# Topics
TOPIC_ORE_BATCH = "ore.batch"           # Digger → Refinery
TOPIC_MINT_INGOTS = "mint.ingots"       # Refinery → Mint
TOPIC_DISTODAM_UNITS = "distodam.units" # Mint → DistoDam

# Timeouts
TIMEOUT_ORE = 30        # Wait for Digger to produce ore
TIMEOUT_INGOT = 90      # Wait for Refinery to produce ingot (13 ores @ 5s = 65s)
TIMEOUT_UNIT = 120      # Wait for Mint to produce Phase3 unit (1000 ingots)


async def test_crypto_pipeline_flow():
    """
    Test complete pipeline flow with crypto signatures
    
    Flow:
    1. Trigger Digger execution
    2. Wait for ore.batch (should have Falcon signature)
    3. Wait for mint.ingots (should have unit-level hashes)
    4. Wait for distodam.units (should have SPHINCS+ signature)
    5. Validate crypto fields at each stage
    
    Returns:
        True if all stages pass, False otherwise
    """
    print_section("E2E Test: Phase 4 Crypto Pipeline Flow")
    
    # Prerequisites
    print_step("Checking prerequisites...")
    
    # Check Digger first
    if not check_docker_container("robotorq-network-digger-1"):
        print_error("Digger container not running")
        print_step("Start services: docker-compose up -d digger")
        return False
    
    containers = [REFINERY_CONTAINER, MINT_CONTAINER, DISTODAM_CONTAINER]
    for container in containers:
        if not check_docker_container(container):
            print_error(f"Container not running: {container}")
            print_step("Start services: docker-compose up -d")
            return False
    
    print_success("All containers running")
    
    # Connect to NATS
    print_step("Connecting to NATS...")
    nc = NATS()
    try:
        await nc.connect(NATS_URL)
        print_success("Connected to NATS")
    except Exception as e:
        print_error(f"Failed to connect to NATS: {e}")
        return False
    
    # Storage for intercepted messages
    ore_message = None
    ingot_message = None
    unit_message = None
    
    # Subscribe to all topics
    async def ore_handler(msg):
        nonlocal ore_message
        try:
            data = json.loads(msg.data.decode())
            ore_message = data
            print_success(f"Intercepted ore.batch: {data.get('contract_id', 'unknown')}")
        except json.JSONDecodeError:
            print_warning("Received non-JSON ore.batch message")
    
    async def ingot_handler(msg):
        nonlocal ingot_message
        try:
            data = json.loads(msg.data.decode())
            ingot_message = data
            print_success(f"Intercepted mint.ingots: {data.get('id', 'unknown')}")
        except json.JSONDecodeError:
            print_warning("Received non-JSON mint.ingots message")
    
    async def unit_handler(msg):
        nonlocal unit_message
        try:
            data = json.loads(msg.data.decode())
            unit_message = data
            print_success(f"Intercepted distodam.units: {data.get('unit_id', 'unknown')}")
        except json.JSONDecodeError:
            print_warning("Received non-JSON distodam.units message")
    
    await nc.subscribe(TOPIC_ORE_BATCH, cb=ore_handler)
    await nc.subscribe(TOPIC_MINT_INGOTS, cb=ingot_handler)
    await nc.subscribe(TOPIC_DISTODAM_UNITS, cb=unit_handler)
    
    print_success("Subscribed to all topics")
    
    # Give subscriptions time to register
    await asyncio.sleep(2)
    
    # Trigger Digger execution
    print_step("Triggering Digger execution...")
    if not await trigger_digger_execution("e2e-crypto-test"):
        print_error("Failed to trigger Digger")
        await nc.close()
        return False
    
    # Wait for ore.batch
    print_step(f"Waiting {TIMEOUT_ORE}s for ore.batch (Digger → Refinery)...")
    for i in range(TIMEOUT_ORE):
        if ore_message:
            break
        await asyncio.sleep(1)
        if (i + 1) % 10 == 0:
            print_step(f"Still waiting... ({i + 1}s)")
    
    if not ore_message:
        print_error("No ore.batch received!")
        print_step("Check Digger logs: docker logs robotorq-network-digger-1 --tail 50")
        await nc.close()
        return False
    
    # Validate ore.batch crypto fields
    print_section("Stage 1: Digger → Refinery (ore.batch)")
    
    ore_valid = True
    
    # Check signature field
    if "signature" not in ore_message:
        print_error("Missing 'signature' field in ore.batch")
        ore_valid = False
    else:
        sig = ore_message["signature"]
        try:
            bytes.fromhex(sig)
            sig_len = len(sig) // 2  # Hex chars to bytes
            print_success(f"Falcon signature present: {sig_len} bytes")
            
            if sig_len < 32:
                print_warning(f"Signature suspiciously small: {sig_len} bytes")
            elif sig_len > 10000:
                print_warning(f"Signature suspiciously large: {sig_len} bytes")
        except ValueError:
            print_error("Signature is not valid hex")
            ore_valid = False
    
    # Check public_key field
    if "public_key" not in ore_message:
        print_error("Missing 'public_key' field in ore.batch")
        ore_valid = False
    else:
        pubkey = ore_message["public_key"]
        try:
            bytes.fromhex(pubkey)
            pubkey_len = len(pubkey) // 2
            print_success(f"Falcon public key present: {pubkey_len} bytes")
            
            # Falcon-1024 public key should be 1793 bytes
            if pubkey_len == 1793:
                print_success("Public key matches Falcon-1024 spec (1793 bytes)")
            else:
                print_warning(f"Public key size unexpected: {pubkey_len} bytes (expected 1793)")
        except ValueError:
            print_error("Public key is not valid hex")
            ore_valid = False
    
    # Show additional ore details
    print_step("Ore details:")
    print(f"  Contract ID: {ore_message.get('contract_id', 'N/A')}")
    print(f"  Digger ID: {ore_message.get('digger_id', 'N/A')}")
    print(f"  Hash count: {len(ore_message.get('hashes', []))}")
    
    if not ore_valid:
        print_error("Ore.batch validation FAILED")
        await nc.close()
        return False
    
    print_success("Ore.batch crypto validation PASSED")
    
    # Wait for mint.ingots
    print_step(f"Waiting {TIMEOUT_INGOT}s for mint.ingots (Refinery → Mint)...")
    for i in range(TIMEOUT_INGOT):
        if ingot_message:
            break
        await asyncio.sleep(1)
        if (i + 1) % 20 == 0:
            print_step(f"Still waiting... ({i + 1}s)")
    
    if not ingot_message:
        print_error("No mint.ingots received!")
        print_step("Check Refinery logs: docker logs robotorq-network-refinery-1 --tail 50")
        await nc.close()
        return False
    
    # Validate mint.ingots structure
    print_section("Stage 2: Refinery → Mint (mint.ingots)")
    
    ingot_valid = True
    
    # Check units array
    if "units" not in ingot_message:
        print_error("Missing 'units' array in ingot")
        ingot_valid = False
    else:
        units = ingot_message["units"]
        unit_count = len(units)
        print_success(f"Ingot contains {unit_count} JouleTorqUnits")
        
        if unit_count != 3600:
            print_warning(f"Unit count unexpected: {unit_count} (expected 3600)")
        
        # Check first unit structure
        if unit_count > 0:
            unit = units[0]
            if "hash" in unit:
                print_success(f"Units have hash field: {unit['hash'][:16]}...")
            else:
                print_warning("Units missing hash field")
    
    # Check branch_hash
    if "branch_hash" not in ingot_message:
        print_error("Missing 'branch_hash' field in ingot")
        ingot_valid = False
    else:
        branch_hash = ingot_message["branch_hash"]
        try:
            bytes.fromhex(branch_hash)
            if len(branch_hash) == 64:  # SHA256 hex
                print_success(f"Branch hash present: {branch_hash[:16]}...")
            else:
                print_warning(f"Branch hash unexpected length: {len(branch_hash)} chars (expected 64)")
        except ValueError:
            print_error("Branch hash is not valid hex")
            ingot_valid = False
    
    # Show additional ingot details
    print_step("Ingot details:")
    print(f"  Ingot ID: {ingot_message.get('id', 'N/A')}")
    print(f"  JouleTorq Total: {ingot_message.get('joule_torq_total', 0):.2f}")
    print(f"  RoboStake Total: {ingot_message.get('robo_stake_total', 0):.6f}")
    print(f"  Contracts: {ingot_message.get('contract_ids', [])}")
    
    if not ingot_valid:
        print_error("Mint.ingots validation FAILED")
        await nc.close()
        return False
    
    print_success("Mint.ingots crypto validation PASSED")
    
    # Wait for distodam.units
    print_step(f"Waiting {TIMEOUT_UNIT}s for distodam.units (Mint → DistoDam)...")
    print_warning("Note: This requires 1000 ingots to accumulate, may take time")
    
    for i in range(TIMEOUT_UNIT):
        if unit_message:
            break
        await asyncio.sleep(1)
        if (i + 1) % 30 == 0:
            print_step(f"Still waiting... ({i + 1}s)")
    
    if not unit_message:
        print_warning("No distodam.units received within timeout")
        print_step("This is expected if < 1000 ingots accumulated")
        print_step("Check Mint logs: docker logs robotorq-network-mint-1 --tail 50")
        print_step("Pipeline flow validated up to Mint stage")
        await nc.close()
        return True  # Partial success
    
    # Validate distodam.units crypto fields
    print_section("Stage 3: Mint → DistoDam (distodam.units)")
    
    unit_valid = True
    
    # Check unit_id
    if "unit_id" not in unit_message:
        print_error("Missing 'unit_id' field in Phase3 unit")
        unit_valid = False
    else:
        unit_id = unit_message["unit_id"]
        print_success(f"Phase3 unit ID: {unit_id}")
    
    # Check merkle_root
    if "merkle_root" not in unit_message:
        print_error("Missing 'merkle_root' field in Phase3 unit")
        unit_valid = False
    else:
        merkle_root = unit_message["merkle_root"]
        try:
            bytes.fromhex(merkle_root)
            if len(merkle_root) == 64:  # SHA256 hex
                print_success(f"Merkle root: {merkle_root[:16]}...")
            else:
                print_warning(f"Merkle root unexpected length: {len(merkle_root)} chars")
        except ValueError:
            print_error("Merkle root is not valid hex")
            unit_valid = False
    
    # Check signature (optional in placeholder mode)
    if "signature" in unit_message:
        sig = unit_message["signature"]
        try:
            bytes.fromhex(sig)
            sig_len = len(sig) // 2
            print_success(f"SPHINCS+ signature present: {sig_len} bytes")
            
            if sig_len < 32:
                print_warning(f"SPHINCS+ signature suspiciously small: {sig_len} bytes")
        except ValueError:
            print_error("SPHINCS+ signature is not valid hex")
            unit_valid = False
    else:
        print_warning("No 'signature' field (placeholder mode)")
    
    # Check public_key (optional in placeholder mode)
    if "public_key" in unit_message:
        pubkey = unit_message["public_key"]
        try:
            bytes.fromhex(pubkey)
            pubkey_len = len(pubkey) // 2
            print_success(f"SPHINCS+ public key present: {pubkey_len} bytes")
        except ValueError:
            print_error("SPHINCS+ public key is not valid hex")
            unit_valid = False
    else:
        print_warning("No 'public_key' field (placeholder mode)")
    
    # Show additional unit details
    print_step("Phase3 unit details:")
    print(f"  Minted at: {unit_message.get('minted_at', 'N/A')}")
    print(f"  Ingot count: {unit_message.get('ingot_count', 0)}")
    
    if not unit_valid:
        print_error("Distodam.units validation FAILED")
        await nc.close()
        return False
    
    print_success("Distodam.units crypto validation PASSED")
    
    # Cleanup
    await nc.close()
    
    # Success summary
    print_section("E2E Crypto Pipeline Flow - SUMMARY")
    print_success("✅ Stage 1: Digger → Refinery (Falcon signatures)")
    print_success("✅ Stage 2: Refinery → Mint (Unit hashes + branch hash)")
    print_success("✅ Stage 3: Mint → DistoDam (SPHINCS+ signatures)")
    print("")
    print_warning("⚠️  REMINDER: This test validates STRUCTURE and FLOW only")
    print_warning("⚠️  Cryptographic validity is NOT verified (placeholders accept all)")
    print_warning("⚠️  Production deployment requires liboqs-go integration")
    print("")
    print_success("🎉 E2E CRYPTO PIPELINE FLOW TEST PASSED!")
    
    return True


async def main():
    """Run the E2E test"""
    try:
        success = await test_crypto_pipeline_flow()
        return 0 if success else 1
    except Exception as e:
        print_error(f"E2E test failed with exception: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    exit(exit_code)
