[package]
name = "robotorq-examples"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
authors = ["RoboTorq Contributors"]

[dependencies]
commons = { path = "../commons", features = ["otlp"], default-features = false }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "signal"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
rand = "0.9.2"
futures-util = "0.3"
http = "1.4.0"
tokio-tungstenite = "0.28.0"
 

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }

[features]
with-otlp = []
## Passthrough feature to enable OTLP in workspace commons from the examples crate
## Allows running: `cargo run --bin emit_traces --features otlp`
otlp = ["commons/otlp"]