[package]
name = "robotorq-examples"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
authors = ["RoboTorq Contributors"]

[dependencies]
commons = { path = "../commons", default-features = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "signal"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }